version: '3.4'

services:
  daylist:
    container_name: daylist
    image: daylist
    restart: always
    environment:
      - DATABASE_URL=
      - NEXT_PUBLIC_API_URL=http://192.168.0.4:3410
      - NEXT_PUBLIC_CLIENT_API_URL=http://192.168.0.4:3410
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
    ports:
      - 3410:3000
    build:
      context: .
      dockerfile: Dockerfile
