version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: daylist
    ports:
      - 5435:5432

  daylist:
    container_name: daylist
    image: daylist
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:docker@192.168.0.4:5435/daylist
      - NEXT_PUBLIC_API_URL=http://192.168.0.4:3410
    ports:
      - 3410:3000
    build:
      context: .
      dockerfile: Dockerfile
