version: '3.4'

services:
  daylist:
    container_name: daylist
    image: daylist
    restart: always
    environment:
      - DATABASE_URL=
      - AUTH_SECRET=
      - NEXTAUTH_URL=http://localhost:3410/api/auth/
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
    ports:
      - 3410:3410
    build:
      context: .
      dockerfile: Dockerfile
